# This is a no-op workflow that has inverse path filtering to test_turnkey.yml

name: Lint and Test TurnkeyML

on:
  pull_request:
    branches: ["main", "canary", "refresh"]
    ignore-paths:
    - src/turnkeyml/**
    - test/turnkey/**
    - examples/turnkey/**
    - .github/workflows/test_turnkey.yml

permissions:
  contents: read

jobs:
  build-turnkey:
      strategy:
          matrix:
            python-version: ["3.8", "3.11"]
            os: [ubuntu-latest, windows-latest]
      runs-on: ubuntu-latest
      steps:
        - run: 'echo "No test_turnkey build required because no files that match the paths filters were changed."'