# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Lemonade Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  make-server-lemonade:
    env:
        LEMONADE_CI_MODE: "True"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Miniconda with 64-bit Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: lemon
          python-version: "3.10"
          run-post: "false"
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip check
          pip install -e .[llm]
      - name: Run server tests
        shell: bash -el {0}
        run: |
          python test/lemonade/server.py


